export {Footer as DocsFooter } from './components/footer'
export { NavBar as DocsNavBar } from './components/navmenu/index'
export { TripleCard as DocsTripleCard } from './components/triplecard'
export { HelpCard as DocsHelpCard } from './components/helpcard'
export * from './components/header'
export * from './components/page'
