name: Release library
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm ci

      - name: Test with Jest
        run: npm run test

      - name: Build library
        run: npm run build

      - name: Build storybook
        run: npm run build-storybook

      - name: Publish storybook build to github pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Publish library to github packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
