name: Release library
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - uses: actions/configure-pages@v2
      - uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build && npm run build-storybook

      - name: Upload artifact.
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./storybook-static/

      - name: Publish storybook build to github pages
        id: deployment
        uses: actions/deploy-pages@v1

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
