name: Release library
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm ci

      - name: Build library and storybook
        run: npm run build

      - name: Setup pages.
        uses: actions/configure-pages@v2
      - name: Upload artifact.
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./storybook-static/
      - name: Publish storybook build to github pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Publish library to github packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
