name: Test library
on:
  pull_request:
    branches:
      - "main"
    paths:
      - src/**
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm ci

      - name: Test with Jest
        run: npm run test

      - name: Build library
        run: npm run build
